### ISSUE TITLE
Failing DDP race condition test on MI50

### ISSUE THREAD

**Issue by hubertlu-tw** [ROCmSoftwarePlatform/apex#65]
The following error messages are captured on MI50 server with the PyTorch build from [IFU-master-2021-12-13](https://github.com/ROCmSoftwarePlatform/pytorch/tree/IFU-master-2021-12-13) when running 

`HIP_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 DDP/ddp_race_condition_test.py`

```
running DDP tests
/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
i = 0
i = 0
model.a: grad.data_ptr() = 140255244058624, expected sum 16777216.0, got 16777216.0
model.a: grad.data_ptr() = 140549851971584, expected sum 16777216.0, got 16777216.0
model.b: grad.data_ptr() = 140281886277632, expected sum 8388608.0, got 8388608.0
model.b: grad.data_ptr() = 140571930787840, expected sum 8388608.0, got 8388608.0
rank 1 created group 0 with backend nccl
rank 1 created group 1 with backend nccl
rank 1 created group 2 with backend nccl
rank 0 created group 0 with backend nccl
rank 0 created group 1 with backend nccl
rank 0 created group 2 with backend nccl
Traceback (most recent call last):
  File "DDP/ddp_race_condition_test.py", line 52, in <module>
    loss.backward()
  File "/opt/conda/lib/python3.6/site-packages/torch/_tensor.py", line 352, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
  File "/opt/conda/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/parallel/distributed.py", line 401, in allreduce_hook
    self.comm_ready_buckets(param)
  File "/opt/conda/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/parallel/distributed.py", line 535, in comm_ready_buckets
    self.allreduce_maybe_retain(self.buckets[bucket_idx], bucket_idx)
  File "/opt/conda/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/parallel/distributed.py", line 480, in allreduce_maybe_retain
    allreduced = self.allreduce_bucket(bucket, bucket_idx, force_default_stream)
  File "/opt/conda/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/parallel/distributed.py", line 450, in allreduce_bucket
    dist.all_reduce(tensor_to_allreduce, group=self.bucket_pgs[bucket_idx%self.num_allreduce_streams])
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1314, in all_reduce
    work = group.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1164, unhandled system error, NCCL version 2.8.4
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
Traceback (most recent call last):
  File "DDP/ddp_race_condition_test.py", line 52, in <module>
    loss.backward()
  File "/opt/conda/lib/python3.6/site-packages/torch/_tensor.py", line 352, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
  File "/opt/conda/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/parallel/distributed.py", line 401, in allreduce_hook
    self.comm_ready_buckets(param)
  File "/opt/conda/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/parallel/distributed.py", line 535, in comm_ready_buckets
    self.allreduce_maybe_retain(self.buckets[bucket_idx], bucket_idx)
  File "/opt/conda/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/parallel/distributed.py", line 480, in allreduce_maybe_retain
    allreduced = self.allreduce_bucket(bucket, bucket_idx, force_default_stream)
  File "/opt/conda/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/parallel/distributed.py", line 450, in allreduce_bucket
    dist.all_reduce(tensor_to_allreduce, group=self.bucket_pgs[bucket_idx%self.num_allreduce_streams])
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1314, in all_reduce
    work = group.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1164, unhandled system error, NCCL version 2.8.4
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 56622) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
DDP/ddp_race_condition_test.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2021-12-15_00:24:52
  host      : d740d63d6dfd
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 56623)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2021-12-15_00:24:52
  host      : d740d63d6dfd
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 56622)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by hubertlu-tw** [comment]
Problem solved by using --shm-size=4g for docker run command on MI50 server.
